### PR TITLE
[URGENT] BUGFIX: trim don't accept null argument

### PR DESCRIPTION
**Pull request by nasserghiasi**
when the user sends another type of request just like document or photo, $text going to null and trim() function throw PHP fatal error.

### CODE REVIEW

**Comment by noplanman** [comment]
@nasserghiasi Wow, thanks for pointing this out!

A better solution in my opinion, would be the following (simply to change `getText` to `getType`):
```php
$text    = $update_content->getType();
```
This will then show the type of message received in the log, instead of the text of a text message.
I think it makes more sense to see what type of message is received instead of the content itself.

This would also be better for privacy reasons 👍 

@jacklul You agree?

**Comment by nasserghiasi** [comment]
I think better choice is you let to developer choose output type

**Comment by nasserghiasi** [comment]
Please fix this bug, I need it

**Comment by noplanman** [comment]
Have you seen the PR I made to your master branch?
https://github.com/nasserghiasi/telegram-bot-manager/pull/1

It's a suggested solution, if you're happy with it, you can merge it and I'll merge here :+1:

**Review by noplanman — APPROVED** [review]

**Comment by noplanman** [comment]
@nasserghiasi Version 1.2.0 has been released, enjoy!

**Pull request merged**
